label variable session_id "session_id"
label variable client_id "client_id"
label variable started_at "started_at"
label variable completed_at "completed_at"
label variable completion_time "completion_time"
label variable consultation_active "consultation_active"
label variable language "language"
label variable is_panel_participant "is_panel_participant"
label variable panel_id "panel_id"
label variable panel_source "panel_source"
label variable b1812_consent__created_at "b1776_consent__created_at"
label variable b1812_consent__consent_given "b1776_consent__consent_given"
label variable b2212_questions__created_at "b2212_questions__created_at"
label variable wann_succesvol_ws "Wanneer vind of vond je jezelf een succesvolle wetenschapper"
label variable overwegen_stoppen "Heb je weleens overwogen om te stoppen als wetenschapper?"
label variable overwegen_stoppen_mot "Waarom?"
label variable belang_reden_ws "Wat is voor jou de belangrijkste reden om in de wetenschap te werken?"
label variable pos_aspecten "Wat zijn voor jou de positieve aspecten van je werk?"
label variable neg_aspecten "En wat zijn de negatieve aspecten?"
label variable wijzigingen_systeem "Als jij het voor het zeggen had: Zou je dan kleine, grote of geen wijzigingen maken aan het Nederlandse wetenschapssysteem?"
label variable wijzigingen_systeem_open "Als je wijzigingen zou maken, welke?"
label variable ondrzksaanvraag_1 "Nee"
label variable ondrzksaanvraag_2 "Ja, een persoonlijke beurs in Nederland"
label variable ondrzksaanvraag_3 "Ja, een persoonlijke beurs in het buitenland, of een Europese beurs"
label variable ondrzksaanvraag_4 "Ja, als leider van een team of consortium"
label variable ondrzksaanvraag_5 "Ja, een onderzoeksvoorstel voor een faculteit"
label variable ondrzksaanvraag_6 "Ja, een onderzoeksvoorstel voor een universiteit"
label variable ondrzksaanvraag_7 "Ja, een onderzoeksvoorstel voor een stichting"
label variable ondrzksaanvraag_8 "Ja, een onderzoeksvoorstel voor een bedrijf of overheid"
label variable onderzoeksaanvraag_open "Andere reden onderzoeksaanvraag"
label variable geen_ondrzksaanvraag_1 "Ik wil dat niet doen."
label variable geen_ondrzksaanvraag_2 "Ik heb dat niet nodig. Ik hoef dat niet te doen van mijn leidinggevende."
label variable geen_ondrzksaanvraag_3 "Ik vind het nog te vroeg in mijn carriere om dat te doen."
label variable geen_ondrzksaanvraag_4 "Ik vind onderwijs belangrijker om mijn tijd in te steken."
label variable geen_ondrzksaanvraag_5 "Ik heb er geen tijd voor."
label variable geen_ondrzksaanvraag_6 "Ik ben bang dat het zonde van mijn tijd is."
label variable geen_ondrzksaanvraag_open "andere reden geen onderzoeksaanvraag"
label variable ondrzksaanvraag_succesvol "Was(waren) je onderzoeksaanvra(a)g(en) gehonoreerd?"
label variable commissie_1 "NWO"
label variable commissie_2 "Binnen mijn eigen universiteit\/faculteit"
label variable commissie_3 "Een Europese of andere buitenlandse financier"
label variable commissie_4 "Een award-commissie"
label variable commissie_5 "Nee"
label variable commissie_open "Onderdeel beoordelingscommissie open"
label variable created_at "0"
label variable ktversie "0"
label variable kt1 "Persoonlijke beurzen voor senior onderzoekers via competitie"
label variable mkt1 "0"
label variable kt2 "Team beurzen voor onderzoeksgroepen met meer dan 2 hoofdonderzoekers"
label variable mkt2 "0"
label variable kt3 "Persoonlijke beurzen voor recent gepromoveerden"
label variable mkt3 "0"
label variable kt4 "Thematisch onderzoek zonder in-cash cofinanciering"
label variable mkt4 "0"
label variable kt5 "Thematisch onderzoek met in-cash cofinanciering"
label variable mkt5 "0"
label variable kt6 "Kleinere beurzen (50-100k) via de universiteit"
label variable mkt6 "0"
label variable kt7 "Kleinere beurzen (50-100k) via NWO"
label variable mkt7 "0"
label variable kt8 "Grote prijzen voor prestaties in wetenschap"
label variable mkt8 "0"
label variable kt9 "Naar universiteiten voor vaste posities voor startende onderzoekers via benoemingscommissies"
label variable mkt9 "0"
label variable kt10 "UDs en UHDs ontvangen geld via universiteit voor eigen onderzoek (rolling grant)"
label variable mkt10 "0"
label variable kt11 "Hoogleraren ontvangen geld via universiteit voor eigen onderzoek (rolling grant)"
label variable mkt11 "0"
label variable ktm_overig "0"

























label variable created_at "0"
label variable ktversie "0"
label variable kt1 "Persoonlijke beurzen voor senior onderzoekers via competitie"
label variable mkt1 "0"
label variable kt2 "Team beurzen voor onderzoeksgroepen met meer dan 2 hoofdonderzoekers"
label variable mkt2 "0"
label variable kt3 "Persoonlijke beurzen voor recent gepromoveerden"
label variable mkt3 "0"
label variable kt4 "Thematisch onderzoek zonder in-cash cofinanciering"
label variable mkt4 "0"
label variable kt5 "Thematisch onderzoek met in-cash cofinanciering"
label variable mkt5 "0"
label variable kt6 "Kleinere beurzen (50-100k) via de universiteit"
label variable mkt6 "0"
label variable kt7 "Kleinere beurzen (50-100k) via NWO"
label variable mkt7 "0"
label variable kt8 "Grote prijzen voor prestaties in wetenschap"
label variable mkt8 "0"
label variable kt9 "Naar universiteiten voor vaste posities voor startende onderzoekers via benoemingscommissies"
label variable mkt9 "0"
label variable kt10 "UDs en UHDs ontvangen geld via universiteit voor eigen onderzoek (rolling grant)"
label variable mkt10 "0"
label variable kt11 "Hoogleraren ontvangen geld via universiteit voor eigen onderzoek (rolling grant)"
label variable mkt11 "0"
label variable ktm_overig "0"
label variable b2215_questions__created_at "b2215_questions__created_at"
label variable rol_persoon_1 "Mijn directe leidinggevende of supervisor"
label variable rol_persoon_2 "Het hoofd van de afdeling"
label variable rol_persoon_3 "De decaan"
label variable rol_persoon_4 "Mijn collega's"
label variable rol_persoon_5 "NWO"
label variable rol_persoon_6 "Het ministerie van OCW"
label variable rol_persoon_7 "Een rolmodel/mentor"
label variable verbeteren_bijdage_ws "Heb je ideeën die de WETENSCHAPPELIJKE bijdrage van jou of jouw collega's zou kunnen verbeteren?"
label variable verbeteren_bijdrage_ms "Heb je ideeën die de MAATSCHAPPELIJKE bijdrage van jou of jouw collega's zou kunnen verbeteren?"
label variable carriere_beinvloed "Heeft je succes of gebrek aan succes in het verkrijgen van onderzoeksfinanciering je carrière beïnvloed?"
label variable carriere_beinvloed_mot "Zo ja, hoe?"
label variable financiering_nodig_1 "Niets, ik ben nu waar ik qua carrierepad wil zijn"
label variable financiering_nodig_2 "Een beurs voor een aantal jaren om mijn eigen baan veilig te stellen"
label variable financiering_nodig_3 "Een beurs om mijn team uit te breiden"
label variable financiering_nodig_4 "Een beurs om wat meer vrijheid te hebben mijn eigen tijd in te delen"
label variable financiering_nodig_5 "Een beurs om apparatuur of infrastructuur aan te schaffen"
label variable financiering_nodig_open "andere reden financiering nodig"
label variable verdeling_1 "Ik denk dat het review proces van onderzoeksbeurzen eerlijk is"
label variable verdeling_2 "Een beurs krijgen is een soort loterij"
label variable verdeling_3 "Ik besteed te veel tijd aan het schrijven van onderzoeksvoorstellen"
label variable verdeling_4 "Ik schrijf onderzoeksvoorstellen over onderwerpen waarmee ik denk dat ik een grotere kans heb om de beurs te krijgen"
label variable wie_bepalen_1 "De uitvoerende onderzoeker"
label variable wie_bepalen_2 "Leidinggevende onderzoekers (projectleiders, professoren)"
label variable wie_bepalen_3 "Universiteiten (op basis van strategie en visies)"
label variable wie_bepalen_4 "Beoordelingscommissies"
label variable wie_bepalen_5 "De overheid"
label variable wie_bepalen_6 "De samenleving"
label variable co_financiering_1 "Co-financiering door private partijen en overheden is een bedreiging voor wetenschappelijke integriteit"
label variable co_financiering_2 "Ik heb goede contacten met private partijen en/of overheden"
label variable co_financiering_3 "Co-financiering is niet relevant voor het type onderzoek dat ik doe"
label variable mening_delen "Wil je nog iets delen over het het onderwerp van deze raadpleging?"
label variable b2216_questions__created_at "b2216_questions__created_at"
label variable uni "Werken bij universiteit"
label variable positie "Positie binnen de wetenschap"
label variable discipline "Discipline"
label variable invloed_persoonlijk_leven "Heb je het gevoel dat je persoonlijke leven en andere verplichtingen je kansen als onderzoeker beïnvloeden?"
label variable tijd_act_1 "Onderzoek"
label variable tijd_act_2 "Onderwijs (inclusief begeleiden studenten)"
label variable tijd_act_3 "Begeleiding van PhD studenten"
label variable tijd_act_4 "Management (laag en middel)"
label variable tijd_act_5 "Management (hoger)"
label variable tijd_act_6 "Academische dienstverlening (training + professioneel onderwijs)"
label variable tijd_act_7 "Administratie"
label variable tijd_act_8 "Medezeggenschap (actief bij vakbonden etc.)"
label variable tijd_act_9 "Patientenzorg"
label variable lft "Leeftijd"
label variable gender "Geslacht"
label variable ervaring_1 "Ik heb genoeg informatie gekregen om een advies te geven"
label variable ervaring_2 "Ik heb vertrouwen in de adviezen die ik heb gegeven"
label variable ervaring_3 "Deze raadpleging helpt academici om meer te weten te komen over onderzoeksfinanciering"
label variable ervaring_4 "Dit soort raadplegingen zouden vaker moeten worden gedaan onder academici"
label variable ervaring_5 "De overheid moet in haar besluitvorming over onderzoeksfinanciering een grote rol toekennen aan de uitkomsten van deze raadpleging"
label variable cijfer "Rapportcijfer"
label variable goed_pwe "Wat vind je goed aan deze raadpleging?"
label variable verbeteren_pwe "Wat zou je verbeteren aan deze raadpleging?"
